import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useDoctorProfile } from '@/hooks/useDoctorProfile';
import { toast } from '@/hooks/use-toast';

export interface Prescription {
  id: string;
  doctor_name: string;
  patient_name: string;
  age: number;
  gender: string;
  contact: string | null;
  temperature: number | null;
  bp: string | null;
  medications: any[];
  notes: string | null;
  follow_up_date: string | null;
  created_at: string;
  updated_at: string;
}

export interface AIAnalysisData {
  id: string;
  prescription_id: string;
  drug_interactions: any[];
  adverse_reactions: any[];
  dosage_validation: any[];
  overall_risk: string | null;
  recommendations: any[];
  alternatives: any[];
  medication_resolutions: any[];
  created_at: string;
}

export interface Patient {
  id: string;
  patient_id: string;
  doctor_id: string;
  full_name: string;
  age: number | null;
  gender: string | null;
  phone_number: string | null;
  address: string | null;
  created_at: string;
  updated_at: string;
}

export interface PatientVisit {
  id: string;
  patient_id: string;
  doctor_id: string;
  visit_date: string;
  reason_for_visit: string | null;
  diagnosis: string | null;
  prescription_id: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export const usePrescriptions = () => {
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([]);
  const [patients, setPatients] = useState<Patient[]>([]);
  const [patientVisits, setPatientVisits] = useState<PatientVisit[]>([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const { profile } = useDoctorProfile();

  const fetchPrescriptions = async () => {
    if (!user) return;

    try {
      const { data, error } = await supabase
        .from('prescriptions')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      const typedData: Prescription[] = (data || []).map(item => ({
        ...item,
        medications: Array.isArray(item.medications) ? item.medications : []
      }));
      
      setPrescriptions(typedData);
    } catch (error) {
      console.error('Error fetching prescriptions:', error);
      toast({
        title: "Error",
        description: "Failed to fetch prescriptions",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchPatients = async () => {
    if (!profile) return;

    try {
      const { data, error } = await supabase
        .from('patients')
        .select('*')
        .eq('doctor_id', profile.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      
      setPatients(data || []);
    } catch (error) {
      console.error('Error fetching patients:', error);
    }
  };

  const fetchPatientVisits = async () => {
    if (!profile) return;

    try {
      const { data, error } = await supabase
        .from('patient_visits')
        .select(`
          *,
          patients (
            patient_id,
            full_name
          ),
          prescriptions (
            doctor_name,
            medications
          )
        `)
        .eq('doctor_id', profile.id)
        .order('visit_date', { ascending: false });

      if (error) throw error;
      
      setPatientVisits(data || []);
    } catch (error) {
      console.error('Error fetching patient visits:', error);
    }
  };

  const findOrCreatePatient = async (patientData: any) => {
    if (!profile) throw new Error('Doctor profile not found');

    // First, try to find existing patient by name and phone
    const { data: existingPatients, error: searchError } = await supabase
      .from('patients')
      .select('*')
      .eq('doctor_id', profile.id)
      .eq('full_name', patientData.patientName)
      .eq('phone_number', patientData.contact || '');

    if (searchError) throw searchError;

    if (existingPatients && existingPatients.length > 0) {
      return existingPatients[0];
    }

    // Create new patient if not found - the patient_id will be auto-generated by the database trigger
    const { data: newPatient, error: createError } = await supabase
      .from('patients')
      .insert({
        doctor_id: profile.id,
        full_name: patientData.patientName,
        age: patientData.age,
        gender: patientData.gender,
        phone_number: patientData.contact,
        address: null // Could be added to the form later
      })
      .select()
      .single();

    if (createError) throw createError;
    
    return newPatient;
  };

  const createPatientVisit = async (patient: any, prescription: any, prescriptionData: any) => {
    if (!profile) throw new Error('Doctor profile not found');

    const { data, error } = await supabase
      .from('patient_visits')
      .insert({
        patient_id: patient.id,
        doctor_id: profile.id,
        visit_date: new Date().toISOString().split('T')[0],
        reason_for_visit: 'Medical consultation',
        diagnosis: prescriptionData.notes || 'General consultation',
        prescription_id: prescription.id,
        notes: prescriptionData.notes
      })
      .select()
      .single();

    if (error) throw error;
    return data;
  };

  const savePrescription = async (prescriptionData: any) => {
    if (!user) throw new Error('User not authenticated');

    try {
      // Save prescription first
      const { data: prescription, error: prescriptionError } = await supabase
        .from('prescriptions')
        .insert({
          user_id: user.id,
          doctor_name: prescriptionData.doctorName,
          patient_name: prescriptionData.patientName,
          age: prescriptionData.age,
          gender: prescriptionData.gender,
          contact: prescriptionData.contact,
          temperature: prescriptionData.temperature,
          bp: prescriptionData.bp,
          medications: prescriptionData.medications,
          notes: prescriptionData.notes,
          follow_up_date: prescriptionData.followUpDate || null
        })
        .select()
        .single();

      if (prescriptionError) throw prescriptionError;

      // Create or find patient
      const patient = await findOrCreatePatient(prescriptionData);
      
      // Create patient visit record
      await createPatientVisit(patient, prescription, prescriptionData);
      
      // Refresh data
      await fetchPrescriptions();
      await fetchPatients();
      await fetchPatientVisits();
      
      return prescription;
    } catch (error) {
      console.error('Error saving prescription:', error);
      throw error;
    }
  };

  const saveAIAnalysis = async (prescriptionId: string, analysisData: any) => {
    if (!user) throw new Error('User not authenticated');

    try {
      const { data, error } = await supabase
        .from('ai_analysis')
        .insert({
          prescription_id: prescriptionId,
          drug_interactions: analysisData.drugInteractions || [],
          adverse_reactions: analysisData.adverseReactions || [],
          dosage_validation: analysisData.dosageValidation || [],
          overall_risk: analysisData.overallRisk,
          recommendations: analysisData.recommendations || [],
          alternatives: analysisData.alternatives || [],
          medication_resolutions: analysisData.medicationResolutions || []
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error saving AI analysis:', error);
      throw error;
    }
  };

  const getAIAnalysis = async (prescriptionId: string): Promise<AIAnalysisData | null> => {
    try {
      const { data, error } = await supabase
        .from('ai_analysis')
        .select('*')
        .eq('prescription_id', prescriptionId)
        .single();

      if (error && error.code !== 'PGRST116') throw error;
      
      if (!data) return null;
      
      const typedData: AIAnalysisData = {
        ...data,
        drug_interactions: Array.isArray(data.drug_interactions) ? data.drug_interactions : [],
        adverse_reactions: Array.isArray(data.adverse_reactions) ? data.adverse_reactions : [],
        dosage_validation: Array.isArray(data.dosage_validation) ? data.dosage_validation : [],
        recommendations: Array.isArray(data.recommendations) ? data.recommendations : [],
        alternatives: Array.isArray(data.alternatives) ? data.alternatives : [],
        medication_resolutions: Array.isArray(data.medication_resolutions) ? data.medication_resolutions : []
      };
      
      return typedData;
    } catch (error) {
      console.error('Error fetching AI analysis:', error);
      return null;
    }
  };

  useEffect(() => {
    if (user && profile) {
      fetchPrescriptions();
      fetchPatients();
      fetchPatientVisits();
    }
  }, [user, profile]);

  return {
    prescriptions,
    patients,
    patientVisits,
    loading,
    savePrescription,
    saveAIAnalysis,
    getAIAnalysis,
    fetchPrescriptions,
    fetchPatients,
    fetchPatientVisits
  };
};
